dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.85
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.85
- name: python-test-1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: spring-test-2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: spring-test-3
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: test-create-spring
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: test-create-spring2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: test-python-jenkins-x
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
